source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'GRKSignatureView', :path => '..'

target 'GRKSignatureViewTestApp' do
  target 'GRKSignatureViewTestAppTests' do
    inherit! :search_paths
  end
end
